name: Bug
description: File a bug report
body:
  - type: markdown
    attributes:
      value: |
        Before opening a bug report, please search for the behaviour in the existing issues. If this is regarding NS functionality, please report to NS customer Support Serivce.
        
        ---
        
        Thank you for taking the time to file a bug report. To address this bug as fast as possible, we need some information.
  - type: dropdown
    id: tool
    attributes:
      label: Select the SuiteCloud tool where you encountered the issue
      options:
        - SuiteCloud CLI
        - SuiteCloud Extension for VSCode
        - SuiteCloud Unit Testing
  - type: input
    id: toolVersion
    attributes:
      label: Version of the SuiteCloud Tool
      description: |
                    For CLI run: `suitecloud --version`

                    For VSCode Extension: `ctrl+shift+x` , search for suitecloud extension, click on uninstall drop down, click on Install Another Version, check current version number

                    For Unit-Testing package: Open package.json from your suitecloud project, check the version on "@oracle/suitecloud-unit-testing": ^1.2.1"
      placeholder: "1.2.0"
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating system
      description: "Which operating system do you use? Please provide the version as well."
      placeholder: "macOS Big Sur 11.5.2"
    validations:
      required: true  
  - type: input
    id: Node
    attributes:
      label: Node Version
      description: "Please provide the full Node version of your project. node -v"
      placeholder: "v18.15.0"
    validations:
      required: true
  - type: input
    id: java
    attributes:
      label: JAVA Version
      description: "Please provide the full Java version. java -version"
      placeholder: "java version '17.0.6 2023-01-17 LTS'"
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: What happened?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. when running suitecloud account:setup ...
        2. creating a new authid
        3. Browser based authentication
        4. See error...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant command output
      description: If applicable, provide relevant command output.
      render: shell
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false 
