define(['./Tab', './Button', './Field', './FieldGroup', './Sublist', '../message/MessageInstance'], function (Tab, Button, Field, FieldGroup, Sublist, Message) {
    /**
     * @class Form
     * @classdesc Primary object used to encapsulate a NetSuite-looking form.
     * After you create a Form object, you can add a variety of scriptable elements to the form including fields, links, buttons, tabs, and sublists.
     * @protected
     * @constructor
     *
     * @since 2015.2
     */
    function Form() {

        /**
         * The form title
         * @name Form#title
         * @type {string}
         *
         * @since 2015.2
         */
        this.title = undefined;
        /**
         * This method is called during a beforeLoad UE or a suitelet and the message is later displayed on the client side,
         * once the pageInit script is completed. The method takes either an already created Message object or the options
         * object that would be used for creating the message.
         * User event context can be used to control whether the message is shown on records in view, create, or edit mode (not applicable for Suitelets).
         * @restriction Server SuiteScript only
         * @governance none
         * @param {Object|Message} options config object OR the message options object to be displayed in browser, described in N/ui/message: create()
         * @param {Message} options.message the message object to be displayed in browser, described in N/ui/message: create()
         * @return {void}
         * @throws {error.SuiteScriptError} WRONG_PARAMETER_TYPE if supplied options parameter is not an object
         *
         * @since 2018.2
         */
        this.addPageInitMessage = function (options) { };

        /**
         * Adds a button to the ui form
         * @restriction Server SuiteScript only
         * @governance none
         * @param {Object} options
         * @param {string} options.id The script id of button. If you are adding the button to an existing page, the id must be in lowercase, contain no spaces, and include the prefix custpage.
         * @param {string} options.label The label of button
         * @param {string} [options.functionName] The function name to be triggered on a click event.
         * @return {Button}
         * @throws {SuiteScriptError} SSS_MISSING_REQD_ARGUMENT when id or label parameter is missing
         *
         * @since 2015.2
         */
        this.addButton = function (options) { };

        /**
         * Adds a text field that lets you store credentials in NetSuite to be used when invoking services provided by third parties. The GUID generated by this field can be reused multiple times until the script executes again.
         * @restriction Server SuiteScript only
         * @governance none
         * @param {Object} options
         * @param {string} options.id The script id of field
         * @param {string} options.label The label of field
         * @param {Array<string>|string} options.restrictToDomains  Domain or list of domains that restricts the destination domains for the credentials, such as 'www.mysite.com'. Credentials cannot be sent to a domain that is not specified here.
         * @param {Array<string>|string} options.restrictToScriptIds  The list of IDs of the scripts where this credential field can be used
         * @param {boolean} [options.restrictToCurrentUser=false] Controls whether the use of this credential is restricted to the same user that originally entered it.
         * By default, the value is false, which means that multiple users can use the credential.
         * @param {string} [options.container]  Id of the form tab where the credential is placed. By default, the field is added to the main section of the form.
         * @return {Field}
         * @throws {SuiteScriptError} SSS_MISSING_REQD_ARGUMENT when any required parameter is missing
         *
         * @since 2015.2
         */
        this.addCredentialField = function (options) { };

        /**
         * Adds a secret key field to the form. This key can be used in crypto modules to perform encryption or hashing.
         * The default maximum length for a secret key field is 32 characters. If needed, use the Field.maxLength property to change this value.
         * @restriction Server SuiteScript only
         * @governance none                                       `
         * @param {Object} options
         * @param {string} options.id The script id of field. The id must be in lowercase, contain no spaces, and include the prefix custpage if you are adding the field to an existing page.
         * @param {string} options.label The UI label for the field.
         * @param {Array<string>|string} [options.restrictToScriptIds]  The list of IDs of the scripts where the key can be used.
         * @param {boolean} [options.restrictToCurrentUser=false] Controls whether use of this secret key is restricted to the same user that originally entered the key. By default, the value is false, which means that multiple users can use the key.
         * @param {string} [options.container]  Id of the form tab or group where the key is placed. By default, the field is added to the main section of the form.
         * @return {Field}
         * @throws {SuiteScriptError} SSS_MISSING_REQD_ARGUMENT when id, label or restrictToScriptIds parameter is missing
         *
         * @since 2015.2
         */
        this.addSecretKeyField = function (options) { };

        /**
         * Adds a field to the form
         * @restriction Server SuiteScript only
         * @governance none
         * @param {Object} options
         * @param {string} options.id Script id for the field. The id must be in lowercase, contain no spaces, and include the prefix custpage if you are adding the field to an existing page.
         * @param {string} options.label UI label for the field
         * @param {string} options.type  Type of the field. Use the serverWidget.FieldType enum to set the field type.
         * @param {string} [options.source]  The internalId or scriptId of the source list for this field if it is a select (List/Record) or multi-select field
         * @param {string} [options.container]   ID of the field group or tab where to place the field. By default, the field is added to the main section of the form.
         * @return {Field}
         * @throws {SuiteScriptError} SSS_MISSING_REQD_ARGUMENT when id, label or type parameter is missing
         *
         * @since 2015.2
         */
        this.addField = function (options) { };

        /**
         * Adds a field group to the form
         * @restriction Server SuiteScript only
         * @governance none
         * @param {Object} options
         * @param {string} options.id the script id for field group
         * @param {string} options.label the label for field group
         * @param {string} [options.tab] ID of the tab where to place the field group. By default, the field group is added to the main section of the form.
         *
         * @return {FieldGroup}
         * @throws {SuiteScriptError} SSS_MISSING_REQD_ARGUMENT when id or label parameter is missing
         *
         * @since 2015.2
         */
        this.addFieldGroup = function (options) { };

        /**
         * Adds a link to the form
         * @restriction Server SuiteScript only
         * @governance none
         * @param {Object} options
         * @param {string} options.type The type of link. Use the serverWidget.FormPageLinkType enum to set the value."
         * @param {string} options.title The UI label for the link.
         * @param {string} options.url The URL for the link.
         * @return {void}
         * @throws {SuiteScriptError} SSS_MISSING_REQD_ARGUMENT when type, title or url parameter is missing
         *
         * @since 2015.2
         */
        this.addPageLink = function (options) { };

        /**
         * Adds a Sublist to the form
         * @restriction Server SuiteScript only
         * @governance none
         * @param {Object} options
         * @param {string} options.id  The script id for the sublist. The id must be in lowercase, contain no spaces, and include the prefix custpage if you are adding the sublist to an existing page.
         * @param {string} options.label The ui label for the sublist
         * @param {string} options.type  The type of sublist. Use the serverWidget.SublistType enum to set the value.
         * @param {string} [options.tab] ID of the tab where to add the sublist to. By default, the sublist is added to the main tab.
         * @return {Sublist}
         * @throws {SuiteScriptError} SSS_MISSING_REQD_ARGUMENT when id, label or type parameter is missing
         *
         * @since 2015.2
         */
        this.addSublist = function (options) { };

        /**
         * Adds a Subtab to the form. In order for your subtab to appear on your form, there must be at least one object assigned to the subtab. Otherwise, the subtab will not appear.
         * @restriction Server SuiteScript only
         * @governance none
         * @param {Object} options
         * @param {string} options.id  The script id for the subtab. The id must be in lowercase, contain no spaces. If you are adding the subtab to an existing page, include the prefix custpage.
         * @param {string} options.label The UI label for the subtab
         * @param {string} [options.tab] The tab under which to display this subtab. If empty, it is added to the main tab.
         * @return {Tab}
         * @throws {SuiteScriptError} SSS_MISSING_REQD_ARGUMENT when id or label parameter is missing
         *
         * @since 2015.2
         */
        this.addSubtab = function (options) { };

        /**
         * Adds a Tab to the form
         * @restriction Server SuiteScript only
         * @governance none
         * @param {Object} options
         * @param {string} options.id  The script id for the Tab. The internal ID must be in lowercase and contain no spaces. If you are adding the tab to an existing page, include the prefix custpage.
         * @param {string} options.label The UI label for the tab
         * @return {Tab}
         * @throws {SuiteScriptError} SSS_MISSING_REQD_ARGUMENT when id or label parameter is missing
         *
         * @since 2015.2
         */
        this.addTab = function (options) { };

        /**
         * Adds a Reset button to the form
         * @restriction Server SuiteScript only
         * @governance none
         * @param {Object} [options]
         * @param {string} [options.label]  The UI label used for this button. If no label is provided, the label defaults to Reset.
         * @return {Button}
         *
         * @since 2015.2
         */
        this.addResetButton = function (options) { };

        /**
         * Adds a Submit button to the form
         * @restriction Server SuiteScript only
         * @governance none
         * @param {Object} [options]
         * @param {string} [options.label] The UI label for this button. If no label is provided, the label defaults to Save.
         * @return {Button}
         *
         * @since 2015.2
         */
        this.addSubmitButton = function (options) { };

        /**
         * Gets a Button object from its script id
         * @restriction Server SuiteScript only
         * @governance none
         * @param {Object} options
         * @param {string} options.id The script id of the button. ID must be in lowercase and contain no spaces.
         * @return {Button}
         * @throws {SuiteScriptError} SSS_MISSING_REQD_ARGUMENT when id parameter is missing
         *
         * @since 2015.2
         */
        this.getButton = function (options) { };

        /**
         * Gets a Field object from its script id
         * @restriction Server SuiteScript only
         * @governance none
         * @param {Object} options
         * @param {string} options.id The script id of the field. ID must be in lowercase and contain no spaces.
         * @return {Field}
         * @throws {SuiteScriptError} SSS_MISSING_REQD_ARGUMENT when id parameter is missing
         *
         * @since 2015.2
         */
        this.getField = function (options) { };

        /**
         * Gets a Subtab object from its script id
         * @restriction Server SuiteScript only
         * @governance none
         * @param {Object} options
         * @param {string} options.id  The script id of the subtab. ID must be in lowercase and contain no spaces.
         * @return {Tab}
         * @throws {SuiteScriptError} SSS_MISSING_REQD_ARGUMENT when id parameter is missing
         *
         * @since 2015.2
         */
        this.getSubtab = function (options) { };

        /**
         * Gets a Subtab object from its script id
         * @restriction Server SuiteScript only
         * @governance none
         * @param {Object} options
         * @param {string} options.id  The script id for the tab. ID must be in lowercase and contain no spaces.
         * @return {Tab}
         * @throws {SuiteScriptError} SSS_MISSING_REQD_ARGUMENT when id parameter is missing
         *
         * @since 2015.2
         */
        this.getTab = function (options) { };

        /**
         * Returns an array that contains all the tabs in a form.
         * @restriction Server SuiteScript only
         * @governance none
         * @return {Array<Tab>}
         *
         * @since 2015.2
         */
        this.getTabs = function () { };

        /**
         * Gets a Sublist object from its script id
         * @restriction Server SuiteScript only
         * @governance none
         * @param {Object} options
         * @param {string} options.id The script id of the Sublist. ID must be in lowercase and contain no spaces.
         * @return {Sublist}
         * @throws {SuiteScriptError} SSS_MISSING_REQD_ARGUMENT when id parameter is missing
         *
         * @since 2015.2
         */
        this.getSublist = function (options) { };

        /**
         * Inserts a field before another field
         * @restriction Server SuiteScript only
         * @governance none
         * @param {Object} options
         * @param {Field} options.field The field to insert
         * @param {string} options.nextfield Id of the field before which the field is inserted.
         * @return {void}
         * @throws {SuiteScriptError} SSS_MISSING_REQD_ARGUMENT when field or nextfield parameter is missing
         *
         * @since 2015.2
         */
        this.insertField = function (options) { };

        /**
         * Inserts a sublist before another sublist
         * @restriction Server SuiteScript only
         * @governance none
         * @param {Object} options
         * @param {Sublist} options.sublist Sublist to insert
         * @param {string} options.nextsublist Id of the sublist before which the sublist is inserted.
         * @return {void}
         * @throws {SuiteScriptError} SSS_MISSING_REQD_ARGUMENT when sublist or nextsublist parameter is missing
         *
         * @since 2015.2
         */
        this.insertSublist = function (options) { };

        /**
         * Inserts a subtab before another subtab
         * @restriction Server SuiteScript only
         * @governance none
         * @param {Object} options
         * @param {Subtab} options.subtab Subtab to insert
         * @param {string} options.nextsub Id of the subtab before which the subtab is inserted.
         * @return {void}
         * @throws {SuiteScriptError} SSS_MISSING_REQD_ARGUMENT when subtab or nextsub parameter is missing
         *
         * @since 2015.2
         */
        this.insertSubtab = function (options) { };

        /**
         * Inserts a Tab before another tab
         * @restriction Server SuiteScript only
         * @governance none
         * @param {Object} options
         * @param {Tab} options.tab Tab to insert
         * @param {string} options.nexttab  Id of the tab before which the tab is inserted.
         * @return {void}
         * @throws {SuiteScriptError} SSS_MISSING_REQD_ARGUMENT when tab or nexttab parameter is missing
         *
         * @since 2015.2
         */
        this.insertTab = function (options) { };

        /**
         * Removes a button.
         * @restriction Server SuiteScript only
         * @governance none
         * @param {Object} options
         * @param {string} options.id Script id of the button to remove. The ID must be in lowercase and contain no spaces.
         * @return {void}
         * @throws {SuiteScriptError} SSS_MISSING_REQD_ARGUMENT when id parameter is missing
         *
         * @since 2015.2
         */
        this.removeButton = function (options) { };

        /**
         * Set the default values of many fields at once
         * @restriction Server SuiteScript only
         * @governance none
         * @param {Object} options
         * @param {Array<Object>} options.values Array of name/value pairs that map field names to field values.
         * @return {void}
         * @throws {SuiteScriptError} SSS_MISSING_REQD_ARGUMENT when values parameter is missing
         *
         * @since 2015.2
         */
        this.updateDefaultValues = function (options) { };

        /**
         * The file cabinet ID of client script file to be used in this form.
         * @name Form#clientScriptFileId
         * @type {number}
         * @throws {SuiteScriptError} PROPERTY_VALUE_CONFLICT When clientScriptModulePath property was set beforehand
         *
         * @since 2015.2
         */
        this.clientScriptFileId = undefined;
        /**
         * The file path of client script file to be used in this form.
         * @name Form#clientScriptModulePath
         * @type {string}
         * @throws {SuiteScriptError} PROPERTY_VALUE_CONFLICT When clientScriptFileId property was set beforehand
         *
         * @since 2015.2
         */
        this.clientScriptModulePath = undefined;
        /**
         * Returns the object type name
         * @restriction Server SuiteScript only
         * @governance none
         * @return {string}
         *
         * @since 2015.2
         */
        this.toString = function () { };

        /**
         * get JSON format of the object
         * @restriction Server SuiteScript only
         * @governance none
         * @return {Object}
         *
         * @since 2015.2
         */
        this.toJSON = function () { };
    }

    return new Form();
});