module.exports = {
	SDK_COMMANDS_METADATA_FILE: 'SDKCommandsMetadata.json',
	NODE_COMMANDS_METADATA_FILE: 'NodeCommandsMetadata.json',
	COMMAND_GENERATORS_METADATA_FILE: 'CommandGenerators.json',
	ACCOUNT_DETAILS_FILENAME: 'account.json',
	SDF_SDK_PATHNAME: '../bin/cli-2019.2.0-SNAPSHOT.jar',
	SDK_INTEGRATION_MODE_JVM_OPTION: '-DintegrationMode',
	AUTHENTICATION_MODE_BASIC: 'BASIC',
	AUTHENTICATION_MODE_TBA: 'TBA',
	DEFAULT_MESSAGES_FILE: '../../messages.json',
	MANIFEST_XML: 'manifest.xml',
	OBJECTS_FOLDER:  'Objects',
	PROJECT_ACP: 'ACCOUNTCUSTOMIZATION',
	PROJECT_SUITEAPP: 'SUITEAPP',
	REST_ROLES_URL: 'https://system.netsuite.com/rest/roles',
	HTTPS_SYSTEM_URL: 'system.netsuite.com',
	PROXY_URL: 'www-proxy-lon.uk.oracle.com',
	PROXY_PORT: '80',
};
