const IS_ALPHANUMERIC_LOWERCASE_REGEX = '[a-z0-9]+';
module.exports = {
	SDK_COMMANDS_METADATA_FILE: 'SDKCommandsMetadata.json',
	NODE_COMMANDS_METADATA_FILE: 'NodeCommandsMetadata.json',
	COMMAND_GENERATORS_METADATA_FILE: 'CommandGenerators.json',
	ACCOUNT_DETAILS_FILENAME: 'account.json',
	SDF_SDK_PATHNAME: '../bin/cli-2019.2.0.jar',
	AUTHENTICATION_MODE_BASIC: 'BASIC',
	AUTHENTICATION_MODE_TBA: 'TBA',
	DEFAULT_MESSAGES_FILE: '../../messages.json',
	MANIFEST_XML: 'manifest.xml',
	MANIFEST_XML_DEFINITIONS: {
		ATTRIBUTES: {
			PROJECT_TYPE: 'projecttype',
		},
		TAGS: {
			MANIFEST: 'manifest',
		},
	},
	SUITEAPP_ID_FORMAT_REGEX:
		'^' + IS_ALPHANUMERIC_LOWERCASE_REGEX + '(\\.' + IS_ALPHANUMERIC_LOWERCASE_REGEX + '){2}$',
	PROJECT_ACP: 'ACCOUNTCUSTOMIZATION',
	PROJECT_SUITEAPP: 'SUITEAPP',
};
