name: Agent Skills CI

on:
  pull_request:
    paths:
      - '.github/workflows/agent-skills-ci.yml'
      - 'package.json'
      - 'package-lock.json'
      - 'packages/agent-skills/**'
  push:
    branches:
      - master
    paths:
      - '.github/workflows/agent-skills-ci.yml'
      - 'package.json'
      - 'package-lock.json'
      - 'packages/agent-skills/**'

jobs:
  validate-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci --workspace @oracle/agent-skills

      - name: Validate Agent Skills
        run: npm run validate --workspace @oracle/agent-skills

      - name: Run tests
        run: npm run test --workspace @oracle/agent-skills
